services:
  - redis-server

language: node_js

node_js:
  - "8.9.1"

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

cache:
  directories:
    - ~/.npm
    - ~/.meteor

notifications:
  email: false

script:
  - meteor create --release 1.8.1 --bare test
  - cd test
  - meteor npm i --save puppeteer@1.18.1 simpl-schema
  - METEOR_PACKAGE_DIRS="../" TEST_BROWSER_DRIVER=puppeteer meteor test-packages --raw-logs --once --driver-package meteortesting:mocha ../
